version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: integration-service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./50x:/etc/nginx/html/errorPages/
    ports:
      - 80:80